// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3UFIIzRS60RqQMTQcCd_guOP10oqDeTw',
    appId: '1:820210859396:web:dde9ef8f44e90b5621b1d1',
    messagingSenderId: '820210859396',
    projectId: 'trackify-app01',
    authDomain: 'trackify-app01.firebaseapp.com',
    storageBucket: 'trackify-app01.firebasestorage.app',
    measurementId: 'G-Y7MQJ41178',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtA0aXg6xVU9HEcmaYinBM2wFhvmy5YJM',
    appId: '1:820210859396:android:96d238c6a82d0dbb21b1d1',
    messagingSenderId: '820210859396',
    projectId: 'trackify-app01',
    storageBucket: 'trackify-app01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcG_0AvnciU-SVHN-zt9xFkXsE-B24lXQ',
    appId: '1:820210859396:ios:8451f889f906cb3c21b1d1',
    messagingSenderId: '820210859396',
    projectId: 'trackify-app01',
    storageBucket: 'trackify-app01.firebasestorage.app',
    iosBundleId: 'com.example.trackifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcG_0AvnciU-SVHN-zt9xFkXsE-B24lXQ',
    appId: '1:820210859396:ios:8451f889f906cb3c21b1d1',
    messagingSenderId: '820210859396',
    projectId: 'trackify-app01',
    storageBucket: 'trackify-app01.firebasestorage.app',
    iosBundleId: 'com.example.trackifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3UFIIzRS60RqQMTQcCd_guOP10oqDeTw',
    appId: '1:820210859396:web:88b8a34dec325acd21b1d1',
    messagingSenderId: '820210859396',
    projectId: 'trackify-app01',
    authDomain: 'trackify-app01.firebaseapp.com',
    storageBucket: 'trackify-app01.firebasestorage.app',
    measurementId: 'G-9D50Y3JW51',
  );
}
